config/routes.rb
Rails.application.routes.draw do
  resources :kintais
  resources :shains
  resources :holidays
  get "/kintais/:dd/new" => "kintais#new", as: :new_kintai_by_dd
end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params.require(:holiday).permit(:yyyy, :mm, :dd, :name)
    end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= form_for @holiday, :html => { :class => "form-horizontal holiday" } do |f| %>

  <% if @holiday.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @holiday.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "日付", :class => 'control-label col-md-1 col-lg-1' %>
    <div class="col-md-4 col-lg-4">
      <div class="row">
        <div class="col-md-4 col-lg-4">
          <div class="row">
            <div class="col-md-8 col-lg-8">
              <%= f.text_field :yyyy, :class => 'form-control', :maxlength => '4' %>
            </div>
            <div class="col-md-1 col-lg-1">
              <div class="row"><div class="text-left" style="line-height: 2.5;">年</div></div>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-lg-3">
          <div class="row">
            <div class="col-md-8 col-lg-8">
              <%= f.text_field :mm,   :class => 'form-control', :maxlength => '2' %>
            </div>
            <div class="col-md-3 col-lg-3">
              <div class="row"><div class="text-left" style="line-height: 2.5;">月</div></div>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-lg-3">
          <div class="row">
            <div class="col-md-8 col-lg-8">
              <%= f.text_field :dd,   :class => 'form-control', :maxlength => '2' %>
            </div>
            <div class="col-md-3 col-lg-3">
              <div class="row"><div class="text-left" style="line-height: 2.5;">日</div></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%=f.error_span(:yyyy) %>
    <%=f.error_span(:mm) %>
    <%=f.error_span(:dd) %>
  </div>
  <div class="form-group">
    <%= f.label "祭日", :class => 'control-label col-md-1 col-lg-1' %>
    <div class="col-md-3 col-lg-3">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-1 col-lg-10">
      <%= f.submit "登録", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                holidays_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/holidays/edit.html.erb
<%- model_class = Holiday -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/holidays/index.html.erb
<%- model_class = Holiday -%>
<div style="width: 100%; padding: 0px 20px 40px 20px;">
<div class="page-header">
  <h1>休日マスタメンテナンス</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>日付</th>
      <th>呼称</th></th>
      <th><div class="text-center">編集　削除</div></th>
    </tr>
  </thead>
  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.yyyy %>/<%= holiday.mm %>/<%= holiday.dd %></td>
        <td><%= holiday.name %></td>
        <td><div class="text-center">
          <%= link_to "　　", edit_holiday_path(holiday), :class => 'btn btn-default btn-xs' %>
          <%= link_to "　　", holiday_path(holiday),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "入力", new_holiday_path, :class => 'btn btn-primary' %>

</div>

app/views/holidays/new.html.erb
<%- model_class = Holiday -%>
<div class="page-header">
  <h1>休日マスタメンテナンス</h1>
</div>
<%= render :partial => 'form' %>

app/views/holidays/show.html.erb
<%- model_class = Holiday -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:yyyy) %>:</strong></dt>
  <dd><%= @holiday.yyyy %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mm) %>:</strong></dt>
  <dd><%= @holiday.mm %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dd) %>:</strong></dt>
  <dd><%= @holiday.dd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @holiday.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              holidays_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_holiday_path(@holiday), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              holiday_path(@holiday),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>