config/routes.rb
Rails.application.routes.draw do
  resources :kintais
  resources :shains
  resources :holidays
  get "/kintais/:dd/new" => "kintais#new", as: :new_kintai_by_dd
end

app/models/kintai.rb
class Kintai < ActiveRecord::Base
end

app/controllers/kintais_controller.rb
class KintaisController < ApplicationController
  before_action :set_kintai, only: [:show, :edit, :update, :destroy]

  # GET /kintais
  # GET /kintais.json
  def index
    # 画面データ連携用ハッシュ
    @mkintai = {}

    # ログイン社員番号
    @@shain_no = '007'
    
    # 処理対象年月取得
    now = Time.current
    @@yyyy = now.strftime("%Y")
    @@mm = now.strftime("%m")
    # 対象年月の月初月末日取得
    cur_day = now.beginning_of_month
    end_day = now.end_of_month

    # 対象年月の勤怠データ取得
    @kintais = Kintai.where(shain_no: @@shain_no, yyyy: @@yyyy, mm: @@mm)
    @tkintai = Hash[@kintais.map{|kintai| [kintai.dd, kintai.attributes]}]

    # 祭日取得
    holidays = Holiday.where(yyyy: @@yyyy, mm: @@mm)
    holidayname = Hash[holidays.map{|holiday| [holiday.dd, holiday.attributes]}]
    
    # サマリ項目
    @defoult_working_days_cnt = (end_day - cur_day).to_i/(60*60*24) + 1
    @working_days_cnt  = 0
    @working_hours_sum = 0
    @extra_hours_sum   = 0
    
    while(cur_day < end_day)
      id = ""
      dd = cur_day.strftime("%d")
      ww = cur_day.strftime("%w")
      dw = cur_day.strftime("%d(#{%w(日 月 火 水 木 金 土)[cur_day.wday]})")
      kintai_kbn    = ""
      start_time    = ""
      end_time      = ""
      normal_hours  = ""
      break_hours   = ""
      working_hours = ""
      extra_hours   = ""
      
      holiday_name  = ""
      
      # 行背景カラー設定
      line_bk_color = ""
      # 土曜日
      if ww == "6" then
        line_bk_color = "aliceblue"
      end
      # 日曜日
      if ww == "0" then
        line_bk_color = "lavenderblush"
      end
      # 休日
      if holidayname[dd] != nil then
        line_bk_color = "lavenderblush"
        holiday_name = holidayname[dd]["name"]
        @defoult_working_days_cnt = @defoult_working_days_cnt - 1
      end
      # 本日
      if cur_day.strftime("%Y%m%d") == now.strftime("%Y%m%d") then
        line_bk_color = "lightyellow"
      end
      
      # 要出勤日数算出
      if ww == "6" or ww == "0" then
        @defoult_working_days_cnt = @defoult_working_days_cnt - 1
      end

      # 勤怠登録がある日
      if @tkintai[dd] != nil
        # Table表文言作成
        id            = @tkintai[dd]["id"]
        kintai_kbn    = @tkintai[dd]["kintai_kbn_cd"]
        start_time    = @tkintai[dd]["start_time"] == nil ? "" : @tkintai[dd]["start_time"].strftime("%H:%M")
        end_time      = @tkintai[dd]["end_time"] == nil ? "" : @tkintai[dd]["end_time"].strftime("%H:%M")
        normal_hours  = @tkintai[dd]["normal_hours"]
        break_hours   = @tkintai[dd]["break_hours"]
        working_hours = (@tkintai[dd]["start_time"] == nil or @tkintai[dd]["end_time"] == nil) ? "" : (@tkintai[dd]["end_time"] - @tkintai[dd]["start_time"])/60/60 - @tkintai[dd]["break_hours"]
        extra_hours   = (@tkintai[dd]["start_time"] == nil or @tkintai[dd]["end_time"] == nil) ? "" : (@tkintai[dd]["end_time"] - @tkintai[dd]["start_time"])/60/60 - @tkintai[dd]["break_hours"] - @tkintai[dd]["normal_hours"]

        # 実績サマリ項目算出
        # 出勤日数
        if kintai_kbn == "0" then
          @working_days_cnt = @working_days_cnt + 1
        end
        # 合計勤務時間
        @working_hours_sum = @working_hours_sum + working_hours.to_f
        # 合計残業時間
        @extra_hours_sum = @extra_hours_sum + extra_hours.to_f
      end
      
      @mkintai[cur_day.strftime("%d")] = {
          "id"            => id \
        , "dd"            => dd \
        , "dw"            => dw \
        , "holiday_name"  => holiday_name \
        , "kintai_kbn"    => kintai_kbn \
        , "start_time"    => start_time \
        , "end_time"      => end_time \
        , "normal_hours"  => normal_hours \
        , "break_hours"   => break_hours \
        , "working_hours" => working_hours \
        , "extra_hours"   => extra_hours \
        , "line_bk_color" => line_bk_color \
      }
      cur_day += 1.day
    end

    @kintais = Kintai.all
  end

  # GET /kintais/1
  # GET /kintais/1.json
  def show
    @show_kintai = {}
    @show_kintai["ymdw"] = afnc_ymdw(@kintai.yyyy, @kintai.mm, @kintai.dd)
    @show_kintai["kintai_kbn"]    = @kintai.kintai_kbn_cd   # おいおい区分名を渡すようにしたい
    @show_kintai["start_time"]    = @kintai.start_time == nil ? "" : @kintai.start_time.strftime("%H:%M")
    @show_kintai["end_time"]      = @kintai.end_time == nil ? "" : @kintai.end_time.strftime("%H:%M")
    @show_kintai["normal_hours"]  = @kintai.normal_hours
    @show_kintai["break_hours"]   = @kintai.break_hours
    @show_kintai["working_hours"] = (@kintai.start_time == nil or @kintai.end_time == nil) ? "" : (@kintai.end_time - @kintai.start_time)/60/60 - @kintai.break_hours
    @show_kintai["extra_hours"]   = (@kintai.start_time == nil or @kintai.end_time == nil) ? "" : (@kintai.end_time - @kintai.start_time)/60/60 - @kintai.break_hours - @kintai.normal_hours
    
  end

  # GET /kintais/new
  def new
    @kintai = Kintai.new
    @kintai.shain_no = @@shain_no
    @kintai.yyyy = @@yyyy
    @kintai.mm = @@mm
    dd = params[:dd]
    @kintai.dd = dd
    @ymdw_disp = afnc_ymdw(@kintai.yyyy, @kintai.mm, dd)
  end

  # GET /kintais/1/edit
  def edit
    @ymdw_disp = afnc_ymdw(@kintai.yyyy, @kintai.mm, @kintai.dd)
    if @kintai.start_time != nil then
      @kintai.start_time = @kintai.start_time.strftime("%H:%M")
    end
    if @kintai.end_time != nil then
      @kintai.end_time = @kintai.end_time.strftime("%H:%M")
    end
    if @kintai.normal_hours == nil then
      @kintai.normal_hours = 7.5
    end
    if @kintai.break_hours == nil then
      @kintai.break_hours = 1.0
    end
  end

  # POST /kintais
  # POST /kintais.json
  def create
    @kintai = Kintai.new(kintai_params)

    respond_to do |format|
      if @kintai.save
        format.html { redirect_to @kintai, notice: 'Kintai was successfully created.' }
        format.json { render :show, status: :created, location: @kintai }
      else
        format.html { render :new }
        format.json { render json: @kintai.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kintais/1
  # PATCH/PUT /kintais/1.json
  def update
    respond_to do |format|
      if @kintai.update(kintai_params)
        format.html { redirect_to @kintai, notice: 'Kintai was successfully updated.' }
        format.json { render :show, status: :ok, location: @kintai }
      else
        format.html { render :edit }
        format.json { render json: @kintai.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kintais/1
  # DELETE /kintais/1.json
  def destroy
    @kintai.destroy
    respond_to do |format|
      format.html { redirect_to kintais_url, notice: 'Kintai was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kintai
      @kintai = Kintai.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kintai_params
      params.require(:kintai).permit(:shain_no \
                                   , :yyyy \
                                   , :mm \
                                   , :dd \
                                   , :kintai_kbn_cd \
                                   , :start_time \
                                   , :end_time \
                                   , :normal_hours \
                                   , :break_hours \
                                   )
    end
end

app/helpers/kintais_helper.rb
module KintaisHelper
end

app/views/kintais/_form.html.erb
<%= form_for @kintai, :html => { :class => "form-horizontal kintai" } do |f| %>

  <% if @kintai.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@kintai.errors.count, "error") %> prohibited this kintai from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @kintai.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<div style="display:none">
  <div class="form-group">
    <%= f.label "社員番号：", :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-2 col-md-2 col-lg-2">
      <%= f.text_field :shain_no, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shain_no) %>
  </div>
  <div class="form-group">
    <%= f.label "年：", :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-2 col-md-2 col-lg-2">
      <%= f.text_field :yyyy, :class => 'form-control' %>
    </div>
    <%=f.error_span(:yyyy) %>
  </div>
  <div class="form-group">
    <%= f.label "月：", :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-2 col-md-2 col-lg-2">
      <%= f.text_field :mm, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mm) %>
  </div>
  <div class="form-group">
    <%= f.label "日：", :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-2 col-md-2 col-lg-2">
      <%= f.text_field :dd, :class => 'form-control' %>
    </div>
    <%=f.error_span(:dd) %>
  </div>
</div>  
  <div class="form-group">
    <%= f.label "勤怠区分：", :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-2 col-md-2 col-lg-2">
      <%= f.text_field :kintai_kbn_cd, :class => 'form-control' %>
    </div>
    <%=f.error_span(:kintai_kbn_cd) %>
  </div>
  
  <div class="form-group">
    <%= f.label "始業時刻：", :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-2 col-md-2 col-lg-2 clockpicker">
      <%= f.text_field :start_time, :class => 'form-control' %>
    </div>
    <script type="text/javascript">
    $('.clockpicker').clockpicker({autoclose: true});
    </script>
    <%=f.error_span(:start_time) %>
  </div>
  
  <div class="form-group">
    <%= f.label "終業時刻：", :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-2 col-md-2 col-lg-2 clockpicker">
      <%= f.text_field :end_time, :class => 'form-control' %>
    </div>
    <script type="text/javascript">
    $('.clockpicker').clockpicker({autoclose: true});
    </script>
    <%=f.error_span(:end_time) %>
  </div>
  
  <div class="form-group">
    <%= f.label "所定時間：", :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-2 col-md-2 col-lg-2">
      <%= f.text_field :normal_hours, :class => 'form-control' %>
    </div>
    <%=f.error_span(:normal_hours) %>
  </div>
  <div class="form-group">
    <%= f.label "休憩時間：", :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-2 col-md-2 col-lg-2">
      <%= f.text_field :break_hours, :class => 'form-control' %>
    </div>
    <%=f.error_span(:break_hours) %>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-md-offset-2 col-lg-offset-2 col-lg-10">
      <%= f.submit "OK", :class => 'btn btn-primary' %>
      <%= link_to 'キャンセル', kintais_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/kintais/edit.html.erb
<%- model_class = Kintai -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/kintais/index.html.erb
<%- model_class = Kintai -%>
<div style="width: 100%; padding: 0px 10px 0px 20px;">
<div class="page-header">
  <h1>勤怠入力</h1>
</div>
<table class="table table-striped table-condensed">
  <thead>
    <tr style="background-color: skyblue">
      <th width="80px" style="min-width:80px;"><div class="text-center">日付</div></th>
      <th width="70px" style="min-width:80px;"><div class="text-center">区分</div></th>
      <th style="min-width:100px;"><div class="text-center">始業時間</div></th>
      <th style="min-width:100px;"><div class="text-center">就業時間</div></th>
      <th class="hidden-xs hidden-sm hidden-md" style="min-width:100px;"><div class="text-center">所定時間</div></th>
      <th class="hidden-xs hidden-sm hidden-md" style="min-width:100px;"><div class="text-center">休憩時間</div></th>
      <th style="min-width:100px;"><div class="text-center">勤務時間</div></th>
      <th style="min-width:100px;"><div class="text-center">残業時間</div></th>
      <!-- <th><div class="text-center">id</div></th> -->
      <th width="50px" style="min-width:50px;"><div class="text-center">入力</div></th>
    </tr>
  </thead>
  <tbody>
    <% @mkintai.each do |mkin| %>
      <% if mkin[1]["line_bk_color"] == "" then %>
      <tr>
      <% else %>
      <tr style="background-color: <%= mkin[1]["line_bk_color"] %>">
      <% end %>
        <% if mkin[1]["holiday_name"] == "" then %>
          <td><div class="text-center"><%= mkin[1]["dw"] %></div></td>
        <% else %>
          <td><div class="text-center" Title="<%= mkin[1]["holiday_name"] %>"><%= mkin[1]["dw"] %></div></td>
        <% end %>
        <td><div class="text-center"><%= mkin[1]["kintai_kbn"] %></div></td>
        <td><div class="text-center"><%= mkin[1]["start_time"] %></div></td>
        <td><div class="text-center"><%= mkin[1]["end_time"] %></div></td>
        <td class="hidden-xs hidden-sm hidden-md"><div class="text-center"><%= mkin[1]["normal_hours"] %></div></td>
        <td class="hidden-xs hidden-sm hidden-md"><div class="text-center"><%= mkin[1]["break_hours"] %></div></td>
        <td><div class="text-center"><%= mkin[1]["working_hours"] %></div></td>
        <td><div class="text-center"><%= mkin[1]["extra_hours"] %></div></td>
        <!-- <td><div class="text-center"><%= mkin[1]["id"] %></div></td> -->
        <td>
          <div class="text-center">
            <% if mkin[1]["id"] == "" %>
              <%= link_to '　', new_kintai_by_dd_path(dd: mkin[1]["dd"]), :class => 'btn btn-default btn-xs' %>
            <% else %>
              <%= link_to '　', edit_kintai_path(mkin[1]["id"]), :class => 'btn btn-default btn-xs' %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
    <tr style="background-color: pink">
      <td><div class="text-center">要出勤日数</div></td>
      <td><div class="text-center">出勤日数</div></td>
      <td></td>
      <td></td>
      <td class="hidden-xs hidden-sm hidden-md"></td>
      <td class="hidden-xs hidden-sm hidden-md"></td>
      <td><div class="text-center">合計勤務時間</div></td>
      <td><div class="text-center">合計残業時間</div></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><div class="text-center"><%= @defoult_working_days_cnt %></div></td>
      <td><div class="text-center"><%= @working_days_cnt %></div></td>
      <td></td>
      <td></td>
      <td class="hidden-xs hidden-sm hidden-md"></td>
      <td class="hidden-xs hidden-sm hidden-md"></td>
      <td><div class="text-center"><%= @working_hours_sum %></div></td>
      <td><div class="text-center"><%= @extra_hours_sum %></div></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

app/views/kintais/new.html.erb
<%- model_class = Kintai -%>
<div class="page-header">
  <h1><%= @ymdw_disp %> 入力</h1>
</div>
<%= render :partial => 'form' %>

app/views/kintais/show.html.erb
<%- model_class = Kintai -%>
<div class="page-header">
  <h1><%= @show_kintai["ymdw"] %> 勤怠</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>勤怠区分:</strong></dt>
  <dd><%= @show_kintai["kintai_kbn"] %></dd>
  <dt><strong>始業時間:</strong></dt>
  <dd><%= @show_kintai["start_time"] %></dd>
  <dt><strong>終業時間:</strong></dt>
  <dd><%= @show_kintai["end_time"] %></dd>
  <dt><strong>規定時間:</strong></dt>
  <dd><%= @show_kintai["normal_hours"] %></dd>
  <dt><strong>休憩時間:</strong></dt>
  <dd><%= @kintai.break_hours %></dd>
  <dt><strong>勤務時間:</strong></dt>
  <dd><%= @show_kintai["working_hours"] %></dd>
  <dt><strong>残業時間:</strong></dt>
  <dd><%= @show_kintai["extra_hours"] %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              kintais_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_kintai_path(@kintai), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              kintai_path(@kintai),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>