config/routes.rb
Rails.application.routes.draw do
  resources :kintais
  resources :shains
  resources :holidays
  get "/kintais/:dd/new" => "kintais#new", as: :new_kintai_by_dd
end

app/models/shain.rb
class Shain < ActiveRecord::Base
end

app/controllers/shains_controller.rb
class ShainsController < ApplicationController
  before_action :set_shain, only: [:show, :edit, :update, :destroy]

  # GET /shains
  # GET /shains.json
  def index
    @shains = Shain.all
  end

  # GET /shains/1
  # GET /shains/1.json
  def show
  end

  # GET /shains/new
  def new
    @shain = Shain.new
  end

  # GET /shains/1/edit
  def edit
  end

  # POST /shains
  # POST /shains.json
  def create
    @shain = Shain.new(shain_params)

    respond_to do |format|
      if @shain.save
        format.html { redirect_to @shain, notice: 'Shain was successfully created.' }
        format.json { render :show, status: :created, location: @shain }
      else
        format.html { render :new }
        format.json { render json: @shain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shains/1
  # PATCH/PUT /shains/1.json
  def update
    respond_to do |format|
      if @shain.update(shain_params)
        format.html { redirect_to @shain, notice: 'Shain was successfully updated.' }
        format.json { render :show, status: :ok, location: @shain }
      else
        format.html { render :edit }
        format.json { render json: @shain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shains/1
  # DELETE /shains/1.json
  def destroy
    @shain.destroy
    respond_to do |format|
      format.html { redirect_to shains_url, notice: 'Shain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shain
      @shain = Shain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shain_params
      params.require(:shain).permit(:no, :name, :name_kana, :login_id, :login_pw, :shain_kbn, :zaiseki_flg)
    end
end

app/helpers/shains_helper.rb
module ShainsHelper
end

app/views/shains/_form.html.erb
<%= form_for @shain, :html => { :class => "form-horizontal shain" } do |f| %>

  <% if @shain.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shain.errors.count, "error") %> prohibited this shain from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shain.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label '社員番号', :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class=" col-sm-2 col-md-2 col-lg-2">
      <%= f.text_field :no, :class => 'form-control' %>
    </div>
    <%=f.error_span(:no) %>
  </div>
  <div class="form-group">
    <%= f.label '氏名', :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-4 col-md-4 col-lg-4">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label '氏名カナ', :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-4 col-md-4 col-lg-4">
      <%= f.text_field :name_kana, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name_kana) %>
  </div>
  <div class="form-group">
    <%= f.label 'ログインID', :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-4 col-md-4 col-lg-4">
      <%= f.text_field :login_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:login_id) %>
  </div>
  <div class="form-group">
    <%= f.label 'ログインパスワード', :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-4 col-md-4 col-lg-4">
      <%= f.text_field :login_pw, :class => 'form-control' %>
    </div>
    <%=f.error_span(:login_pw) %>
  </div>
  <div class="form-group">
    <%= f.label '社員区分', :class => 'control-label col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-sm-4 col-md-4 col-lg-4">
      <%= f.text_field :shain_kbn, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shain_kbn) %>
  </div>
  <div class="form-group">
    <%= f.label '在籍', :class => 'control-label col-xs-12 col-sm-2 col-md-2 col-lg-2' %>
    <div class="col-xs-3 col-sm-1 col-md-1 col-lg-1">
      <%= f.check_box :zaiseki_flg, :class => 'form-control' %>
    </div>
    <%=f.error_span(:zaiseki_flg) %>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit @submit_value, :class => 'btn btn-primary' %>
      <%= link_to '取消', shains_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<!--
<%= form_for @shain, :html => { :class => "form-horizontal shain" } do |f| %>

  <% if @shain.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shain.errors.count, "error") %> prohibited this shain from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shain.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :no, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :no, :class => 'form-control' %>
    </div>
    <%=f.error_span(:no) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :name_kana, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name_kana, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name_kana) %>
  </div>
  <div class="form-group">
    <%= f.label :login_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :login_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:login_id) %>
  </div>
  <div class="form-group">
    <%= f.label :login_pw, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :login_pw, :class => 'form-control' %>
    </div>
    <%=f.error_span(:login_pw) %>
  </div>
  <div class="form-group">
    <%= f.label :shain_kbn, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shain_kbn, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shain_kbn) %>
  </div>
  <div class="form-group">
    <%= f.label :zaiseki_flg, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :zaiseki_flg, :class => 'form-control' %>
    </div>
    <%=f.error_span(:zaiseki_flg) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "一覧", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shains_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
-->

app/views/shains/edit.html.erb
<%- model_class = Shain -%>
<div class="page-header">
  <h1>社員情報編集</h1>
</div>
<%= render :partial => 'form' %>

app/views/shains/index.html.erb
<%- model_class = Shain -%>
<div style="width: 100%; padding: 0px 20px 40px 20px;">
<div class="page-header">
  <h1>社員マスタメンテナンス</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><div class="text-center">社員番号</div></th>
      <th>氏名</th>
      <th>氏名かな</th>
      <th>ログインID</th>
      <th>ログインPW</th>
      <th><div class="text-center">社員区分</div></th>
      <th><div class="text-center">在籍</div></th>
      <th><div class="text-center">編集　削除</div></th>
    </tr>
  </thead>
  <tbody>
    <% @shains.each do |shain| %>
      <tr>
        <td><div class="text-center"><%= shain.no %></div></td>
        <td><%= shain.name %></td>
        <td><%= shain.name_kana %></td>
        <td><%= shain.login_id %></td>
        <td><%= shain.login_pw %></td>
        <td><div class="text-center"><%= shain.shain_kbn %></div></td>
        <td><div class="text-center"><%= shain.zaiseki_flg == true ? '○' : '×' %></div></td>
        <td><div class="text-center">
          <%= link_to "　　",
                      edit_shain_path(shain), :class => 'btn btn-default btn-xs' %>
          <%= link_to "　　",
                      shain_path(shain),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shain_path,
            :class => 'btn btn-primary' %>
</div>

app/views/shains/new.html.erb
<%- model_class = Shain -%>
<div class="page-header">
  <h1>新規社員登録</h1>
</div>
<%= render :partial => 'form' %>

app/views/shains/show.html.erb
<%- model_class = Shain -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:no) %>:</strong></dt>
  <dd><%= @shain.no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @shain.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_kana) %>:</strong></dt>
  <dd><%= @shain.name_kana %></dd>
  <dt><strong><%= model_class.human_attribute_name(:login_id) %>:</strong></dt>
  <dd><%= @shain.login_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:login_pw) %>:</strong></dt>
  <dd><%= @shain.login_pw %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shain_kbn) %>:</strong></dt>
  <dd><%= @shain.shain_kbn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zaiseki_flg) %>:</strong></dt>
  <dd><%= @shain.zaiseki_flg %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              shains_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shain_path(@shain), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shain_path(@shain),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>